[build]

    command = 'npm run build'
    publish = 'dist'

[[headers]]

    for = '/*'

    [headers.values]

        Strict-Transport-Security = 'max-age=63072000; preload'
        Content-Security-Policy = "default-src 'self'; script-src 'self' www.google-analytics.com; img-src 'self' www.google-analytics.com"
        X-Content-Type-Options = 'nosniff'
        X-Frame-Options = 'DENY'
        X-XSS-Protection = '1; mode=block'

[[redirects]]

    from = "https://thirsty-austin-e8545b.netlify.com/*"
    to = "https://openjck.com/:splat"
    status = 302
    force = true
